# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_cao_bravo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static\\images')),
                ('titulo', models.CharField(max_length=256)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
