# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_cao_bravo', '0003_auto_20191127_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 27, 21, 13, 56, 752000, tzinfo=utc)),
        ),
    ]
