# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_cao_bravo', '0005_auto_20191127_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 27, 21, 16, 48, 4000, tzinfo=utc)),
        ),
    ]
