# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cao_bravo', '0006_auto_20191127_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 28, 12, 34, 34, 921000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=tinymce.models.HTMLField(),
        ),
    ]
